from typing import List
from src.analytics import PlayerScoutingData, Badge

def get_mock_match_data() -> List[PlayerScoutingData]:
    """Generates the exact 10-player match breakdown from the Porofessor reference screenshot."""
    
    return [
        # ==================== BLUE TEAM (TOP ROW) ====================
        PlayerScoutingData(
            game_name="Optimus Prime",
            tag_line="FEUR",
            champion_name="Urgot",
            team_id=100,
            assigned_position="TOP",
            level=1081,
            profile_icon_id=588,
            spell1_name="flash",
            spell2_name="teleport",
            champion_mastery_level=209,
            champion_kills_str="6.2",
            champion_deaths_str="3.7",
            champion_assists_str="4.7",
            champion_wins=117,
            champion_games=201,
            champion_server_rank="Rank: #80",
            tier="GRANDMASTER",
            rank="",
            league_points=807,
            ranked_wins=198,
            ranked_losses=164,
            server_rank="Rank: #4,608",
            twelve_hr_games=2,
            twelve_hr_wins=2,
            thirty_day_games=277,
            thirty_day_wins=162,
            main_role="Top",
            badges=[
                Badge("Good CSer", "good", "Averages high CS per minute"),
                Badge("Godlike Urgot", "good", "Extremely high win rate on Urgot"),
                Badge("OTP Urgot", "good", "Champion Specialist"),
                Badge("Invader", "warning", "Frequent early game invades"),
                Badge("Split Pusher", "warning", "Focuses on side-lane pressure"),
            ]
        ),
        PlayerScoutingData(
            game_name="Danza Kuduro",
            tag_line="Tokyo",
            champion_name="Viego",
            team_id=100,
            assigned_position="JUNGLE",
            level=89,
            profile_icon_id=548,
            spell1_name="flash",
            spell2_name="smite",
            champion_mastery_level=21,
            champion_kills_str="9.5",
            champion_deaths_str="4.3",
            champion_assists_str="6.5",
            champion_wins=92,
            champion_games=148,
            champion_server_rank="Rank: #1,067",
            tier="GRANDMASTER",
            rank="",
            league_points=885,
            ranked_wins=142,
            ranked_losses=89,
            server_rank="Rank: #3,943",
            twelve_hr_games=7,
            twelve_hr_wins=5,
            thirty_day_games=224,
            thirty_day_wins=141,
            main_role="Jungler",
            badges=[
                Badge("Aggressive Jungler", "good", "High early lane ganking frequency"),
                Badge("Viego lover", "good", "High match count on Viego"),
                Badge("Good vision", "good", "Places high quantity of control wards"),
            ]
        ),
        PlayerScoutingData(
            game_name="star zall",
            tag_line="twtv",
            champion_name="Veigar",
            team_id=100,
            assigned_position="MIDDLE",
            level=429,
            profile_icon_id=502,
            spell1_name="teleport",
            spell2_name="flash",
            champion_mastery_level=298,
            champion_kills_str="4.8",
            champion_deaths_str="5.4",
            champion_assists_str="6.8",
            champion_wins=76,
            champion_games=158,
            champion_server_rank="Rank: #176",
            tier="GRANDMASTER",
            rank="",
            league_points=865,
            ranked_wins=521,
            ranked_losses=488,
            server_rank="Rank: #4,086",
            twelve_hr_games=1,
            twelve_hr_wins=0,
            thirty_day_games=158,
            thirty_day_wins=76,
            main_role="Mid",
            badges=[
                Badge("Millionaire: Veigar", "good", "Over 1M mastery points on Veigar"),
                Badge("OTP Veigar", "good", "One Trick Pony on Veigar"),
            ]
        ),
        PlayerScoutingData(
            game_name="Damon Salvatore",
            tag_line="1302",
            champion_name="Ziggs",
            team_id=100,
            assigned_position="BOTTOM",
            level=135,
            profile_icon_id=530,
            spell1_name="teleport",
            spell2_name="flash",
            champion_mastery_level=3,
            champion_kills_str="5.0",
            champion_deaths_str="2.0",
            champion_assists_str="5.0",
            champion_wins=1,
            champion_games=1,
            champion_server_rank="Rank: -",
            tier="GRANDMASTER",
            rank="",
            league_points=881,
            ranked_wins=127,
            ranked_losses=76,
            server_rank="Rank: #3,963",
            twelve_hr_games=1,
            twelve_hr_wins=1,
            thirty_day_games=109,
            thirty_day_wins=68,
            main_role="AD Carry",
            badges=[
                Badge("Pro: 3XA", "pro", "Verified Pro / Semi-pro Player"),
                Badge("Ziggs casual", "danger", "Low games on Ziggs"),
            ]
        ),
        PlayerScoutingData(
            game_name="Mi Innocenti",
            tag_line="sahri",
            champion_name="Nami",
            team_id=100,
            assigned_position="UTILITY",
            level=119,
            profile_icon_id=512,
            spell1_name="heal",
            spell2_name="flash",
            champion_mastery_level=12,
            champion_kills_str="0.8",
            champion_deaths_str="3.1",
            champion_assists_str="13.9",
            champion_wins=5,
            champion_games=8,
            champion_server_rank="Rank: #2,027",
            tier="GRANDMASTER",
            rank="",
            league_points=750,
            ranked_wins=138,
            ranked_losses=95,
            server_rank="Rank: #5,160",
            twelve_hr_games=0,
            twelve_hr_wins=0,
            thirty_day_games=25,
            thirty_day_wins=16,
            main_role="Support",
            badges=[
                Badge("Aggressive Laner", "good", "High forward poke in lane"),
                Badge("Waking up", "warning", "First game of the day"),
                Badge("Roaming", "warning", "High roams to mid lane"),
            ]
        ),

        # ==================== RED TEAM (BOTTOM ROW) ====================
        PlayerScoutingData(
            game_name="twtvSpoodersuss1",
            tag_line="EUWW",
            champion_name="Olaf",
            team_id=200,
            assigned_position="TOP",
            level=592,
            profile_icon_id=560,
            spell1_name="ghost",
            spell2_name="flash",
            champion_mastery_level=23,
            champion_kills_str="4.0",
            champion_deaths_str="5.0",
            champion_assists_str="0.0",
            champion_wins=0,
            champion_games=1,
            champion_server_rank="Rank: #6,129",
            tier="CHALLENGER",
            rank="",
            league_points=1320,
            ranked_wins=322,
            ranked_losses=266,
            server_rank="Rank: #370",
            twelve_hr_games=0,
            twelve_hr_wins=0,
            thirty_day_games=110,
            thirty_day_wins=61,
            main_role="Top",
            badges=[
                Badge("Waking up", "warning", "First game of the day"),
            ]
        ),
        PlayerScoutingData(
            game_name="patience",
            tag_line="966",
            champion_name="Talon",
            team_id=200,
            assigned_position="JUNGLE",
            level=479,
            profile_icon_id=570,
            spell1_name="flash",
            spell2_name="smite",
            champion_mastery_level=45,
            champion_kills_str="10.8",
            champion_deaths_str="4.6",
            champion_assists_str="7.6",
            champion_wins=16,
            champion_games=19,
            champion_server_rank="Rank: #91",
            tier="CHALLENGER",
            rank="",
            league_points=1223,
            ranked_wins=733,
            ranked_losses=692,
            server_rank="Rank: #612",
            twelve_hr_games=3,
            twelve_hr_wins=2,
            thirty_day_games=110,
            thirty_day_wins=67,
            main_role="Jungler",
            badges=[
                Badge("Aggressive Jungler", "good", "High early map dominance"),
                Badge("Godlike Talon", "good", "84% win rate on Talon"),
                Badge("High Kill Participation", "good", "Involved in >65% of team kills"),
                Badge("Epic Stealer", "good", "Frequent Baron & Dragon steals"),
                Badge("Viego stomper", "good", "High win rate vs Viego"),
            ]
        ),
        PlayerScoutingData(
            game_name="Chiacchieronaa",
            tag_line="Emi",
            champion_name="Vladimir",
            team_id=200,
            assigned_position="MIDDLE",
            level=303,
            profile_icon_id=580,
            spell1_name="ghost",
            spell2_name="flash",
            champion_mastery_level=92,
            champion_kills_str="5.8",
            champion_deaths_str="3.8",
            champion_assists_str="4.9",
            champion_wins=68,
            champion_games=134,
            champion_server_rank="Rank: #430",
            tier="GRANDMASTER",
            rank="",
            league_points=733,
            ranked_wins=479,
            ranked_losses=437,
            server_rank="Rank: #5,311",
            twelve_hr_games=1,
            twelve_hr_wins=0,
            thirty_day_games=251,
            thirty_day_wins=119,
            main_role="Mid",
            badges=[
                Badge("Good CSer", "good", "Strong mid-lane wave management"),
                Badge("Vladimir lover", "good", "High game count on Vladimir"),
            ]
        ),
        PlayerScoutingData(
            game_name="24 時間",
            tag_line="OPEN",
            champion_name="Draven",
            team_id=200,
            assigned_position="BOTTOM",
            level=905,
            profile_icon_id=590,
            spell1_name="cleanse",
            spell2_name="flash",
            champion_mastery_level=10,
            champion_kills_str="6.4",
            champion_deaths_str="3.6",
            champion_assists_str="3.0",
            champion_wins=4,
            champion_games=5,
            champion_server_rank="Rank: -",
            tier="GRANDMASTER",
            rank="",
            league_points=749,
            ranked_wins=230,
            ranked_losses=193,
            server_rank="Rank: #5,170",
            twelve_hr_games=8,
            twelve_hr_wins=4,
            thirty_day_games=151,
            thirty_day_wins=84,
            main_role="AD Carry",
            badges=[
                Badge("Aggressive Laner", "good", "Trades aggressively in lane"),
                Badge("Good CSer", "good", "High creep score"),
                Badge("Great with Draven", "good", "80% win rate on Draven"),
                Badge("Good vision", "good", "Maintains river vision"),
            ]
        ),
        PlayerScoutingData(
            game_name="Cribob",
            tag_line="EUW0",
            champion_name="Thresh",
            team_id=200,
            assigned_position="UTILITY",
            level=308,
            profile_icon_id=595,
            spell1_name="ignite",
            spell2_name="flash",
            champion_mastery_level=149,
            champion_kills_str="1.9",
            champion_deaths_str="6.0",
            champion_assists_str="16.1",
            champion_wins=3,
            champion_games=9,
            champion_server_rank="Rank: #2,851",
            tier="DIAMOND",
            rank="I",
            league_points=75,
            ranked_wins=305,
            ranked_losses=270,
            server_rank="Rank: #89,248",
            twelve_hr_games=2,
            twelve_hr_wins=1,
            thirty_day_games=9,
            thirty_day_wins=3,
            main_role="Support",
            badges=[
                Badge("Aggressive Laner", "good", "Frequent forward hook attempts"),
                Badge("Millionaire: Thresh", "good", "Mastery Level 149"),
                Badge("High Kill Participation", "good", "High team fight presence"),
                Badge("Good vision", "good", "High vision score"),
                Badge("Roaming", "warning", "Frequent river roams"),
                Badge("Vulnerable Laner", "danger", "High death risk in lane"),
            ]
        ),
    ]
