from typing import List
from src.analytics import PlayerScoutingData, RecentMatchSummary, AnalyticsEngine, Badge

def get_mock_match_data() -> List[PlayerScoutingData]:
    """Generates a realistic 10-player match breakdown (5 Blue Team vs 5 Red Team)."""
    
    players = [
        # --- BLUE TEAM (Team 100 - Allies) ---
        PlayerScoutingData(
            game_name="VanguardX",
            tag_line="EUW",
            champion_name="Aatrox",
            team_id=100,
            assigned_position="TOP",
            level=6,
            tier="EMERALD",
            rank="I",
            league_points=84,
            ranked_wins=82,
            ranked_losses=68,
            champion_games=34,
            champion_wins=22,
            recent_kills=7.2,
            recent_deaths=3.4,
            recent_assists=5.8,
            recent_matches=[
                RecentMatchSummary("Aatrox", 9, 2, 6, True),
                RecentMatchSummary("Aatrox", 6, 4, 8, True),
                RecentMatchSummary("Aatrox", 8, 3, 5, True),
                RecentMatchSummary("Renekton", 4, 5, 2, False),
                RecentMatchSummary("Aatrox", 9, 3, 8, True),
            ]
        ),
        PlayerScoutingData(
            game_name="ShadowPath",
            tag_line="777",
            champion_name="LeeSin",
            team_id=100,
            assigned_position="JUNGLE",
            level=6,
            tier="DIAMOND",
            rank="IV",
            league_points=42,
            ranked_wins=145,
            ranked_losses=120,
            champion_games=68,
            champion_wins=44,
            recent_kills=6.4,
            recent_deaths=2.2,
            recent_assists=9.8,
            recent_matches=[
                RecentMatchSummary("LeeSin", 8, 1, 11, True),
                RecentMatchSummary("LeeSin", 5, 2, 10, True),
                RecentMatchSummary("LeeSin", 7, 3, 8, True),
                RecentMatchSummary("LeeSin", 6, 2, 12, True),
                RecentMatchSummary("JarvanIV", 4, 3, 14, True),
            ]
        ),
        PlayerScoutingData(
            game_name="GlaivePlayer",
            tag_line="YOU",
            champion_name="Sylas",
            team_id=100,
            assigned_position="MIDDLE",
            level=7,
            tier="DIAMOND",
            rank="III",
            league_points=75,
            ranked_wins=112,
            ranked_losses=88,
            champion_games=25,
            champion_wins=16,
            recent_kills=8.6,
            recent_deaths=4.0,
            recent_assists=6.2,
            recent_matches=[
                RecentMatchSummary("Sylas", 11, 3, 7, True),
                RecentMatchSummary("Sylas", 7, 5, 4, False),
                RecentMatchSummary("Sylas", 10, 4, 8, True),
                RecentMatchSummary("Ahri", 5, 2, 9, True),
                RecentMatchSummary("Sylas", 9, 6, 3, False),
            ]
        ),
        PlayerScoutingData(
            game_name="SilverBullet",
            tag_line="ADC",
            champion_name="Jinx",
            team_id=100,
            assigned_position="BOTTOM",
            level=5,
            tier="EMERALD",
            rank="II",
            league_points=18,
            ranked_wins=55,
            ranked_losses=52,
            champion_games=4,
            champion_wins=1,
            recent_kills=4.2,
            recent_deaths=6.8,
            recent_assists=4.4,
            recent_matches=[
                RecentMatchSummary("Jinx", 3, 8, 2, False),
                RecentMatchSummary("Jinx", 4, 7, 5, False),
                RecentMatchSummary("KaiSa", 2, 6, 3, False),
                RecentMatchSummary("Jinx", 5, 6, 6, True),
                RecentMatchSummary("Caitlyn", 7, 7, 7, False),
            ]
        ),
        PlayerScoutingData(
            game_name="LunarEcho",
            tag_line="SUP",
            champion_name="Thresh",
            team_id=100,
            assigned_position="UTILITY",
            level=5,
            tier="EMERALD",
            rank="I",
            league_points=95,
            ranked_wins=90,
            ranked_losses=70,
            champion_games=45,
            champion_wins=29,
            recent_kills=1.2,
            recent_deaths=3.0,
            recent_assists=14.6,
            recent_matches=[
                RecentMatchSummary("Thresh", 2, 2, 18, True),
                RecentMatchSummary("Thresh", 0, 4, 12, True),
                RecentMatchSummary("Nautilus", 1, 3, 15, True),
                RecentMatchSummary("Thresh", 1, 3, 13, True),
                RecentMatchSummary("Thresh", 2, 3, 15, True),
            ]
        ),

        # --- RED TEAM (Team 200 - Enemies) ---
        PlayerScoutingData(
            game_name="BladeDancer",
            tag_line="KR",
            champion_name="Irelia",
            team_id=200,
            assigned_position="TOP",
            level=6,
            tier="MASTER",
            rank="",
            league_points=140,
            ranked_wins=190,
            ranked_losses=135,
            champion_games=85,
            champion_wins=58,
            recent_kills=9.4,
            recent_deaths=4.2,
            recent_assists=4.8,
            recent_matches=[
                RecentMatchSummary("Irelia", 12, 3, 5, True),
                RecentMatchSummary("Irelia", 8, 5, 4, True),
                RecentMatchSummary("Irelia", 11, 4, 6, True),
                RecentMatchSummary("Irelia", 7, 6, 4, False),
                RecentMatchSummary("Camille", 9, 3, 5, True),
            ]
        ),
        PlayerScoutingData(
            game_name="NocturneNight",
            tag_line="001",
            champion_name="Viego",
            team_id=200,
            assigned_position="JUNGLE",
            level=6,
            tier="DIAMOND",
            rank="II",
            league_points=50,
            ranked_wins=78,
            ranked_losses=72,
            champion_games=18,
            champion_wins=9,
            recent_kills=5.8,
            recent_deaths=5.4,
            recent_assists=6.0,
            recent_matches=[
                RecentMatchSummary("Viego", 4, 6, 5, False),
                RecentMatchSummary("Viego", 7, 5, 7, True),
                RecentMatchSummary("Kayn", 3, 7, 4, False),
                RecentMatchSummary("Viego", 8, 4, 8, True),
                RecentMatchSummary("Viego", 6, 5, 6, False),
            ]
        ),
        PlayerScoutingData(
            game_name="AzureWind",
            tag_line="MID",
            champion_name="Yasuo",
            team_id=200,
            assigned_position="MIDDLE",
            level=7,
            tier="DIAMOND",
            rank="I",
            league_points=12,
            ranked_wins=210,
            ranked_losses=195,
            champion_games=120,
            champion_wins=72,
            recent_kills=8.2,
            recent_deaths=7.6,
            recent_assists=4.4,
            recent_matches=[
                RecentMatchSummary("Yasuo", 10, 8, 3, True),
                RecentMatchSummary("Yasuo", 4, 10, 2, False),
                RecentMatchSummary("Yasuo", 11, 6, 6, True),
                RecentMatchSummary("Yone", 5, 8, 5, False),
                RecentMatchSummary("Yasuo", 12, 6, 7, True),
            ]
        ),
        PlayerScoutingData(
            game_name="DeadEye",
            tag_line="SNIP",
            champion_name="Jhin",
            team_id=200,
            assigned_position="BOTTOM",
            level=5,
            tier="DIAMOND",
            rank="III",
            league_points=88,
            ranked_wins=64,
            ranked_losses=46,
            champion_games=28,
            champion_wins=19,
            recent_kills=7.8,
            recent_deaths=2.6,
            recent_assists=8.2,
            recent_matches=[
                RecentMatchSummary("Jhin", 9, 2, 10, True),
                RecentMatchSummary("Jhin", 8, 1, 7, True),
                RecentMatchSummary("Jhin", 6, 4, 9, True),
                RecentMatchSummary("Ezreal", 5, 3, 6, True),
                RecentMatchSummary("Jhin", 11, 3, 9, True),
            ]
        ),
        PlayerScoutingData(
            game_name="FrostGuard",
            tag_line="CC",
            champion_name="Lulu",
            team_id=200,
            assigned_position="UTILITY",
            level=5,
            tier="DIAMOND",
            rank="IV",
            league_points=30,
            ranked_wins=52,
            ranked_losses=48,
            champion_games=12,
            champion_wins=6,
            recent_kills=0.8,
            recent_deaths=4.2,
            recent_assists=12.0,
            recent_matches=[
                RecentMatchSummary("Lulu", 1, 4, 14, True),
                RecentMatchSummary("Lulu", 0, 5, 8, False),
                RecentMatchSummary("Nami", 2, 3, 11, True),
                RecentMatchSummary("Lulu", 0, 4, 15, True),
                RecentMatchSummary("Lulu", 1, 5, 9, False),
            ]
        ),
    ]

    # Compute badges for each player
    for p in players:
        p.badges = AnalyticsEngine.compute_player_badges(p)

    return players
